version: '3.1'

services:
    # client:
    #     build:
    #         context: ../client/
    #         dockerfile: Dockerfile-prod
    #     container_name: client
    #     volumes:
    #         - ../client:/usr/app
    #         - /usr/app/node_modules
    #     networks:
    #         my-network:
    #             aliases:
    #                 - client
    #     ports:
    #         - "3000:3000"
    db:
        image: mysql
        container_name: rioservice_db
        restart: always
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            my-network:
                aliases:
                    - db
        ports:
            - "3306:3306"
        expose:
            - "3306"
    server:
        build:
            context: ../
            dockerfile: server/Dockerfile
        container_name: server
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: db
            MYSQL_DATABASE: ${DB_NAME}
        command: gunicorn -b 0.0.0.0:5000 -w 1 --pythonpath /var/www/ "server.create_app:create_app(False)"
        volumes:
            - ../server:/var/www/server
        networks:
            my-network:
                aliases:
                    - server
        depends_on:
            - db
    nginx:
        image: nginx:1.15
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ../client/build:/usr/share/nginx/html
            - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
        command: sh -c "sleep 15s;"
        ports:
            - 80:80
        networks:
            - my-network
        depends_on:
            - server
            # - client
networks:
    my-network: